SaleWeb33/Controllers/BrandController.cs
using SaleWeb33.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace SaleWeb33.Controllers
{
    public class BrandController : Controller
    {
        SaledbContext da = new SaledbContext();
        // GET: BrandController
        public ActionResult ListBrands()
        {
            List<Brand> list = da.Brands.Select(s => s).ToList();
            return View(list);
        }

        // GET: BrandController/Details/5
        public ActionResult Details(int id)
        {
            Brand b = da.Brands.Where(s => s.BrandId == id).FirstOrDefault();
            return View(b);
        }

        // GET: BrandController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BrandController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Brand b,IFormCollection collection)
        {
            try
            {
                if (da.Brands.FirstOrDefault(s => s.BrandId == b.BrandId) == null)
                {
                    da.Brands.Add(b);
                    da.SaveChanges();

                    return RedirectToAction("ListBrands");
                }
                else
                {
                    return RedirectToAction("Create");
                }

            }
            catch
            {
                return View();
            }
        }
        // GET: BrandController/Edit/5
        public ActionResult Edit(int id)
        {
            Brand b = da.Brands.FirstOrDefault(s => s.BrandId == id);
            return View(b);
        }

        // POST: BrandController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Brand brand, IFormCollection collection)
        {
            using (var tran = da.Database.BeginTransaction())
            {
                try
                {
                    Brand b = da.Brands.FirstOrDefault(s => s.BrandId == brand.BrandId);
                    b.BrandName = brand.BrandName;

                    da.Brands.Update(b);
                    da.SaveChanges();

                    tran.Commit();

                    return RedirectToAction("ListBrands");
                }
                catch (Exception)
                {
                    tran.Rollback();
                    return View();
                }
            }
        }

        // GET: BrandController/Delete/5
        public ActionResult Delete(int id)
        {
            Brand b = da.Brands.FirstOrDefault(s => s.BrandId == id);
            return View(b);
        }

        // POST: BrandController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            Brand b = da.Brands.FirstOrDefault(s => s.BrandId == id);
            try
            {
                da.Brands.Remove(b);
                da.SaveChanges();
            }
            catch (SqlException ex)
            {
                ViewBag.EX = ex;
                return RedirectToAction("Delete");
            }

            return RedirectToAction("ListBrands");
        }
    }
}

SaleWeb33/Controllers/OrderController.cs
using SaleWeb33.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Drawing.Drawing2D;
using Microsoft.EntityFrameworkCore;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SaleWeb33.Controllers
{
    public class OrderController : Controller
    {
        SaledbContext da = new SaledbContext();
        // GET: OrderController
        public ActionResult ListOrders()
        {
            List<Order> list = da.Orders.Select(s => s).ToList();
            return View(list);
        }

        // GET: OrderController/Details/5
        public ActionResult Details(int id)
        {
            Order o = da.Orders.FirstOrDefault(s => s.OrderId == id);

            return View(o);
        }

        // GET: OrderController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order o, IFormCollection collection)
        {
            try
            {
                if (da.Orders.FirstOrDefault(s => s.OrderId == o.OrderId) == null)
                {
                    da.Orders.Add(o);
                    da.SaveChanges();

                    return RedirectToAction("ListOrder");
                }
                else
                {
                    return RedirectToAction("Create");
                }

            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Edit/5
        public ActionResult Edit(int id)
        {
            Order o = da.Orders.FirstOrDefault(s => s.OrderId == id);
            return View(o);
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Order order, IFormCollection collection)
        {
            using (var tran = da.Database.BeginTransaction())
            {
                try
                {
                    Order o = da.Orders.FirstOrDefault(s => s.OrderId == order.OrderId);
                    o.UserId = order.UserId;
                    o.OrderDate = order.OrderDate;
                    o.ShippingAddress = order.ShippingAddress;

                    da.Orders.Update(o);
                    da.SaveChanges();

                    tran.Commit();

                    return RedirectToAction("ListOrders");
                }
                catch (Exception)
                {
                    tran.Rollback();
                    return View();
                }
            }
        }

        // GET: OrderController/Delete/5
        public ActionResult Delete(int id)
        {
            Order o = da.Orders.FirstOrDefault(s => s.OrderId == id);
            return View(o); ;
        }

        // POST: OrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            Order o = da.Orders.FirstOrDefault(s => s.OrderId == id);
            try
            {
                da.Orders.Remove(o);
                da.SaveChanges();
            }
            catch (SqlException ex)
            {
                ViewBag.EX = ex;
                return RedirectToAction("Delete");
            }

            return RedirectToAction("ListOrders");
        }
    }
}

SaleWeb33/Controllers/ShopController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SaleWeb33.Extensions;
using SaleWeb33.Models;

namespace SaleWeb33.Controllers
{

    public class ShopController : BaseController
    {
        SaledbContext da = new SaledbContext();
        // GET: ShopController
        [Route("/")]
        public ActionResult Index()
        {
            ViewModel viewModel = new ViewModel();
            viewModel.Products = GetProducts();
            return View(viewModel);

        }

        [Route("/products/{id}")]
        public ActionResult ProductDetails(int id)
        {
            Product p = da.Products.Where(s => s.ProductId == id).Include(p => p.Brand)
                                  .Include(p => p.Category)
                                  .Include(p => p.Color)
                                  .Include(p => p.Size).FirstOrDefault();
            return View(p);
        }

        [Route("/categories/{id}")]
        public ActionResult Categories(int id)
        {
            List<Product> ds = da.Products.Where(s => s.CategoryId == id).ToList();
            return View(ds);
        }

        public List<Product> GetProducts()
        {

            List<Product> ds = da.Products.Include(p => p.Brand)
                                    .Include(p => p.Category)
                                    .Include(p => p.Color)
                                    .Include(p => p.Size)
                                    .ToList();

            return ds;
        }

    }
}

SaleWeb33/Controllers/UserController.cs
using SaleWeb33.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace SaleWeb33.Controllers
{
    public class UserController : Controller
    {
        SaledbContext da = new SaledbContext();
        // GET: UserController
        public ActionResult ListUsers()
        {
            List<User> ds = da.Users.Select(s => s).ToList();

            return View(ds);
        }

        // GET: UserController/Details/5
        public ActionResult Details(int id)
        {
            User u = da.Users.FirstOrDefault(s => s.UserId == id);
            return View(u);
        }

        // GET: UserController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User u, IFormCollection collection)
        {
            try
            {
                if (da.Users.FirstOrDefault(s => s.Username == u.Username) == null)
                {
                    da.Users.Add(u);
                    da.SaveChanges();

                    return RedirectToAction("ListUsers");
                }
                else
                {
                    return RedirectToAction("Create");
                }

            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Edit/5
        public ActionResult Edit(int id)
        {
            User u = da.Users.FirstOrDefault(s => s.UserId == id);
            return View(u);
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user, IFormCollection collection)
        {

            using (var tran = da.Database.BeginTransaction())
            {
                try
                {
                    User u = da.Users.FirstOrDefault(s => s.UserId == user.UserId);
                    u.Username = user.Username;
                    u.Password = user.Password;
                    u.FullName = user.FullName;
                    u.Phone = user.Phone;
                    u.Address = user.Address;
                    u.Role = user.Role;

                    da.Users.Update(u);
                    da.SaveChanges();

                    tran.Commit();

                    return RedirectToAction("ListUsers");
                }
                catch (Exception)
                {
                    tran.Rollback();
                    return View();
                }
            }
        }

        // GET: UserController/Delete/5
        public ActionResult Delete(int id)
        {
            User u = da.Users.FirstOrDefault(s => s.UserId == id);
            return View(u);
        }

        // POST: UserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            User u = da.Users.FirstOrDefault(s=>s.UserId == id);
            try
            {
                da.Users.Remove(u);
                da.SaveChanges();
            }
            catch(SqlException ex)
            {
                ViewBag.EX = ex;
                return RedirectToAction("Delete");
            }

            return RedirectToAction("ListUsers");
        }
    }
}

SaleWeb33/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SaleWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SaleWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SaleWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="ListCategories">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="ListBrands">Brand</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="ListOrders">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="ListUsers">User</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SaleWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SaleWeb33/Views/Shared/_Layout_shop.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SaleWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Index.css" />
</head>
<body class="container">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Shop" asp-action="Index">SaleWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Categories" asp-route-id="1">Snapback</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Categories" asp-route-id="2">Jacket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Categories" asp-route-id="3">Lưỡi trai</a>
                        </li>
                        <li class="nav-item ms-auto">
                            <a class="nav-link text-dark d-flex" asp-area="" asp-controller="Cart" asp-action="ListCarts">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag mt-1" viewBox="0 0 16 16">
                                    <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z" />
                                </svg>
                                <div class="mt-0 ms-1">
                                    <small>@ViewBag.demSL</small>
                                </div>
                              
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row justify-content-center">
            <div class="p-2">
              <div class="col md-12 mb-0 text-center">
                <p>
                  <Link
                    class="h6 link-secondary link-underline-opacity-0 link-opacity-75-hover"
                   
                  >
                    Home
                  </Link>
                  <Link
                    class="h6 link-secondary link-underline-opacity-0 link-opacity-75-hover m-2"
                   
                  >
                    About
                  </Link>
                  <Link
                    class="h6 link-secondary link-underline-opacity-0 link-opacity-75-hover"
                   
                  >
                    Contact
                  </Link>
                </p>
                <p>2023 Copyright All rights reserved</p>
              </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>